/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { Suspense, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { useSpring, animated, easings } from '@react-spring/three'
import { useVideoTexture } from '@react-three/drei';
import urlRight from './screenRight.mp4'
import urlLeft from './screenLeft.mp4'

export function Model({scrollDistanceFromTop}) {
  const { nodes, materials } = useGLTF('/roomFinalTexture.glb')
  
  const [videoRight] = useState(() => {
    const vid = document.createElement("video");
    vid.src = "https://roombackends3.s3.eu-north-1.amazonaws.com/screenRight.mp4";
    vid.crossOrigin = "Anonymous";
    vid.loop = true;
    vid.muted = true;
    vid.play();
    return vid;
  });

  const [videoLeft] = useState(() => {
    const vid = document.createElement("video");
    vid.src = urlLeft;
    vid.crossOrigin = "Anonymous";
    vid.loop = true;
    vid.muted = true;
    vid.play();
    return vid;
  });

  const { positionY } = useSpring({
    cancel: scrollDistanceFromTop < 1.63,
    loop: {reverse: true},
    from: {positionY: -0.2},
    to: {positionY: 0.2},
    config: { duration: 4000, easing: easings.easeInOutSine},
    reset: scrollDistanceFromTop < 1.64

  })

  const { positionZ } = useSpring({
    cancel: scrollDistanceFromTop < 1.63,
    loop: {reverse: true},
    from: {positionZ: 0},
    to: {positionZ: -3},
    config: { duration: 10000, easing: easings.easeInOutSine},
    reset: scrollDistanceFromTop < 1.64
  })

  return (
    <animated.group position-y={positionY} position-z={positionZ} scale={1} rotation={[0,1.5 * Math.PI,0]} dispose={null}>
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Table.geometry} material={materials.Desk} position={[1.1, 2, -2.47]} scale={[1, 0.08, 2.35]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.GroundDeskSupport.geometry} material={materials.White} position={[1.1, 0, -4.66]} scale={[0.9, -0.02, -0.15]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Leg1.geometry} material={materials.White} position={[1.1, 1.51, -4.66]} scale={[-0.08, -0.4, -0.09]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.GroundDeskSupport002.geometry} material={materials.White} position={[1.1, 0, -0.29]} scale={[0.9, -0.02, -0.15]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Leg1002.geometry} material={materials.White} position={[1.1, 1.51, -0.29]} scale={[-0.08, -0.4, -0.09]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.ScreenRighr.geometry} material={materials['Material.001']} position={[0.71, 3.37, -3.53]} rotation={[0, -0.11, 0]} scale={[0.06, 0.67, 1]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.ScreenLeft.geometry} material={materials['Material.001']} position={[0.62, 3.41, -1.5]} rotation={[0, 0.11, 0]} scale={[0.06, 0.67, 1]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.ScreenRightHandle.geometry} material={materials['Material.001']} position={[0.39, 2.73, -3.54]} rotation={[-1.57, 0, 1.46]} scale={0.12} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cylinder.geometry} material={materials['Material.002']} position={[0.38, 2.23, -3.53]} scale={[0.23, -0.02, 0.23]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.ScreenRightCylinder.geometry} material={materials['Material.001']} position={[0.38, 2.22, -3.54]} scale={[0.23, -0.02, 0.23]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube.geometry} material={materials['Material.001']} position={[0.62, 2.12, -2.99]} rotation={[0, -1.11, 0]} scale={[0.39, 0.03, 0.04]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube001.geometry} material={materials['Material.001']} position={[0.18, 2.12, -3.18]} rotation={[Math.PI, -1.07, Math.PI]} scale={[0.18, 0.02, 0.03]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube002.geometry} material={materials.ScreenHolder} position={[0.53, 2.49, -1.5]} scale={[0.38, 0.03, 0.88]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube003.geometry} material={materials.ScreenHolder} position={[0.53, 2.27, -0.68]} scale={[0.38, 0.19, 0.04]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube004.geometry} material={materials.ScreenHolder} position={[0.53, 2.26, -1.51]} scale={[0.38, 0.03, 0.79]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube005.geometry} material={materials.ScreenHolder} position={[0.53, 2.27, -0.68]} scale={[0.38, 0.19, 0.04]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube006.geometry} material={materials.ScreenHolder} position={[0.53, 2.27, -2.33]} scale={[0.38, 0.19, 0.04]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Plane.geometry} material={materials['Material.001']} position={[0.49, 2.53, -1.49]} rotation={[0, 0.09, -0.01]} scale={[0.33, 0.38, 0.38]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube007.geometry} material={materials['Material.001']} position={[0.56, 2.37, -4.59]} rotation={[0, -0.31, 0]} scale={[0.04, 0.25, 0.09]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cylinder001.geometry} material={materials.White} position={[0.62, 2.42, -4.57]} rotation={[-1.6, -0.1, 1.26]} scale={[-0.1, -0.03, -0.1]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cylinder002.geometry} material={materials['Material.001']} position={[0.53, 2.41, -4.6]} rotation={[-1.6, -0.1, 1.26]} scale={[-0.08, -0.06, -0.08]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube008.geometry} material={materials['Material.001']} position={[0.57, 2.09, -4.59]} rotation={[0, -0.31, 0]} scale={[0.1, 0.005, 0.1]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube009.geometry} material={materials['Material.001']} position={[0.52, 2.13, -4.6]} rotation={[0, -0.31, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cylinder003.geometry} material={materials['Material.001']} position={[0.6, 2.18, -4.69]} rotation={[Math.PI / 2, 0, 0.31]} scale={0.02} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube010.geometry} material={materials['Material.001']} position={[0.62, 2.37, -0.31]} rotation={[0, 0.34, 0]} scale={[0.04, 0.25, 0.09]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cylinder004.geometry} material={materials.White} position={[0.68, 2.42, -0.33]} rotation={[-1.54, -0.1, 1.92]} scale={[-0.1, -0.03, -0.1]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cylinder005.geometry} material={materials['Material.001']} position={[0.59, 2.41, -0.29]} rotation={[-1.54, -0.1, 1.92]} scale={[-0.08, -0.06, -0.08]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube011.geometry} material={materials['Material.001']} position={[0.63, 2.09, -0.31]} rotation={[0, 0.34, 0]} scale={[0.1, 0.005, 0.1]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube012.geometry} material={materials['Material.001']} position={[0.58, 2.13, -0.29]} rotation={[0, 0.34, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cylinder006.geometry} material={materials['Material.001']} position={[-0.31, 2.09, -0.47]} rotation={[-Math.PI, 0.05, Math.PI / 2]} scale={[0.015, -1.21, 0.015]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube013.geometry} material={materials['Material.001']} position={[1.47, 2.09, -3.61]} scale={[0.53, -0.01, 0.77]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cylinder007.geometry} material={materials['Material.001']} position={[1.51, 2.1, -3.91]} rotation={[0, 0, -Math.PI / 2]} scale={[0.13, 0.17, 0.1]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube014.geometry} material={materials['Material.001']} position={[1.43, 2.13, -2.4]} rotation={[0.01, 0, 0]} scale={[0.28, 0.03, 0.8]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube015.geometry} material={materials.Keyboard} position={[1.33, 2.2, -1.65]} rotation={[0.01, 0, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube016.geometry} material={materials.Keyboard} position={[1.33, 2.22, -2.9]} rotation={[0.01, 0, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube017.geometry} material={materials.Keyboard} position={[1.23, 2.2, -1.78]} rotation={[0.01, 0, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube018.geometry} material={materials.Keyboard} position={[1.23, 2.2, -2.18]} rotation={[0.01, 0, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube019.geometry} material={materials.Keyboard} position={[1.23, 2.21, -2.62]} rotation={[0.01, 0, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube020.geometry} material={materials.Keyboard} position={[1.23, 2.2, -1.65]} rotation={[0.01, 0, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube021.geometry} material={materials.Keyboard} position={[1.65, 2.21, -2.62]} rotation={[0.01, 0, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube022.geometry} material={materials.Keyboard} position={[1.57, 2.21, -2.7]} rotation={[0.01, 0, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube023.geometry} material={materials.Keyboard} position={[1.33, 2.2, -1.65]} rotation={[0.01, 0, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube024.geometry} material={materials.Keyboard} position={[1.33, 2.2, -1.65]} rotation={[0.01, 0, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube025.geometry} material={materials.Keyboard} position={[1.33, 2.2, -1.65]} rotation={[0.01, 0, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube026.geometry} material={materials.Keyboard} position={[1.33, 2.2, -1.65]} rotation={[0.01, 0, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube027.geometry} material={materials.Keyboard} position={[1.33, 2.2, -1.65]} rotation={[0.01, 0, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube028.geometry} material={materials.Keyboard} position={[1.33, 2.2, -1.65]} rotation={[0.01, 0, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube029.geometry} material={materials.Keyboard} position={[1.33, 2.2, -1.65]} rotation={[0.01, 0, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube030.geometry} material={materials.Keyboard} position={[1.33, 2.2, -1.65]} rotation={[0.01, 0, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube031.geometry} material={materials.Keyboard} position={[1.33, 2.2, -1.65]} rotation={[0.01, 0, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube032.geometry} material={materials.Keyboard} position={[1.33, 2.2, -1.65]} rotation={[0.01, 0, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube033.geometry} material={materials.Keyboard} position={[1.33, 2.2, -1.65]} rotation={[0.01, 0, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube034.geometry} material={materials.Keyboard} position={[1.33, 2.2, -1.65]} rotation={[0.01, 0, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube035.geometry} material={materials.Keyboard} position={[1.33, 2.2, -1.65]} rotation={[0.01, 0, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube036.geometry} material={materials.Keyboard} position={[1.33, 2.2, -1.65]} rotation={[0.01, 0, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube037.geometry} material={materials.Keyboard} position={[1.33, 2.2, -1.65]} rotation={[0.01, 0, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube038.geometry} material={materials.Keyboard} position={[1.33, 2.2, -1.65]} rotation={[0.01, 0, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube039.geometry} material={materials.Keyboard} position={[1.33, 2.2, -1.65]} rotation={[0.01, 0, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube040.geometry} material={materials.Keyboard} position={[1.33, 2.2, -1.65]} rotation={[0.01, 0, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube042.geometry} material={materials.Keyboard} position={[1.33, 2.2, -1.65]} rotation={[0.01, 0, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube043.geometry} material={materials.Keyboard} position={[1.33, 2.2, -1.65]} rotation={[0.01, 0, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube044.geometry} material={materials.Keyboard} position={[1.33, 2.2, -1.65]} rotation={[0.01, 0, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube045.geometry} material={materials.Keyboard} position={[1.33, 2.2, -1.65]} rotation={[0.01, 0, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube047.geometry} material={materials.Keyboard} position={[1.33, 2.2, -1.65]} rotation={[0.01, 0, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube048.geometry} material={materials.Keyboard} position={[1.33, 2.2, -1.65]} rotation={[0.01, 0, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube049.geometry} material={materials.Keyboard} position={[1.33, 2.2, -1.65]} rotation={[0.01, 0, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube050.geometry} material={materials.Keyboard} position={[1.33, 2.2, -1.65]} rotation={[0.01, 0, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube052.geometry} material={materials.Keyboard} position={[1.33, 2.2, -1.65]} rotation={[0.01, 0, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube053.geometry} material={materials.Keyboard} position={[1.33, 2.2, -1.65]} rotation={[0.01, 0, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube054.geometry} material={materials.Keyboard} position={[1.33, 2.2, -1.65]} rotation={[0.01, 0, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube055.geometry} material={materials.Keyboard} position={[1.33, 2.2, -1.65]} rotation={[0.01, 0, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube057.geometry} material={materials.Keyboard} position={[1.33, 2.2, -1.65]} rotation={[0.01, 0, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube058.geometry} material={materials.Keyboard} position={[1.33, 2.2, -1.65]} rotation={[0.01, 0, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube059.geometry} material={materials.Keyboard} position={[1.33, 2.2, -1.65]} rotation={[0.01, 0, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube060.geometry} material={materials.Keyboard} position={[1.33, 2.2, -1.65]} rotation={[0.01, 0, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube062.geometry} material={materials.Keyboard} position={[1.33, 2.2, -1.65]} rotation={[0.01, 0, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube063.geometry} material={materials.Keyboard} position={[1.33, 2.2, -1.65]} rotation={[0.01, 0, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube064.geometry} material={materials.Keyboard} position={[1.33, 2.2, -1.65]} rotation={[0.01, 0, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube065.geometry} material={materials.Keyboard} position={[1.33, 2.2, -1.65]} rotation={[0.01, 0, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube066.geometry} material={materials.Keyboard} position={[1.33, 2.2, -1.65]} rotation={[0.01, 0, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube067.geometry} material={materials.Keyboard} position={[1.33, 2.2, -1.65]} rotation={[0.01, 0, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube068.geometry} material={materials.Keyboard} position={[1.33, 2.2, -1.65]} rotation={[0.01, 0, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube069.geometry} material={materials.Keyboard} position={[1.33, 2.2, -1.65]} rotation={[0.01, 0, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube070.geometry} material={materials.Keyboard} position={[1.33, 2.2, -1.65]} rotation={[0.01, 0, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube071.geometry} material={materials.Keyboard} position={[1.33, 2.2, -1.65]} rotation={[0.01, 0, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube072.geometry} material={materials.Keyboard} position={[1.33, 2.2, -1.65]} rotation={[0.01, 0, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube073.geometry} material={materials.Keyboard} position={[1.33, 2.2, -1.65]} rotation={[0.01, 0, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube074.geometry} material={materials.Keyboard} position={[1.33, 2.2, -1.65]} rotation={[0.01, 0, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube075.geometry} material={materials.Keyboard} position={[1.33, 2.2, -1.65]} rotation={[0.01, 0, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube076.geometry} material={materials.Keyboard} position={[1.33, 2.2, -1.65]} rotation={[0.01, 0, 0]} scale={0.03} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.ScreenRighr001.geometry} position={[0.71, 3.37, -3.53]} rotation={[0, -0.11, 0]} scale={[0.06, 0.67, 1]}>
        <Suspense fallback={<FallbackMaterial/>}>
          <VideoMaterial url="https://roombackends3.s3.eu-north-1.amazonaws.com/screenRight.mp4" />
        </Suspense>
      </mesh>
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.ScreenLeft001.geometry} position={[0.62, 3.41, -1.5]} rotation={[0, 0.11, 0]} scale={[0.06, 0.67, 1]} >
        <meshStandardMaterial>
          <videoTexture attach="map" args={[videoLeft]}/>
        </meshStandardMaterial>
      </mesh>
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Plane002.geometry} material={materials.Floor} position={[3.99, 0, -3.99]} scale={4} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cylinder008.geometry} material={materials['Material.001']} position={[0.62, 2.42, -4.57]} rotation={[-1.6, -0.1, 1.26]} scale={[-0.1, -0.03, -0.1]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Plane003.geometry} material={materials.White} position={[5.19, 2.07, 0.02]} scale={[3.97, 4, 4]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cylinder009.geometry} material={materials['Material.001']} position={[0.68, 2.42, -0.33]} rotation={[-1.54, -0.1, 1.92]} scale={[-0.1, -0.03, -0.1]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cylinder010.geometry} material={materials.White} position={[4.39, 3.9, 0.2]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.04} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cylinder011.geometry} material={materials.White} position={[4.39, 3.9, 0.25]} rotation={[Math.PI / 2, 0, 0]} scale={[0.05, 0.04, 0.16]} />
      <group position={[3.99, 0, -3.99]} scale={4}>
        <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Plane005_1.geometry} material={materials.White} />
        <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Plane005_2.geometry} material={materials.Walls} />
      </group>
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cylinder012.geometry} material={materials.Pot} position={[4.59, 2.29, -0.03]} rotation={[-Math.PI, 0.25, -Math.PI]} scale={0.19} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Plane023.geometry} material={materials.Plant} position={[4.39, 2.59, -0.35]} rotation={[2.51, 1.12, -1.68]} scale={[0.01, 0.02, 0.02]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Plane006.geometry} material={materials.Plant} position={[4.73, 2.58, -0.35]} rotation={[0.45, 0.92, 0.51]} scale={[0.01, 0.02, 0.02]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Plane007.geometry} material={materials.Plant} position={[5.1, 2.64, -0.02]} rotation={[0.26, -0.11, 0.91]} scale={[0.01, 0.04, 0.04]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Plane008.geometry} material={materials.Plant} position={[4.39, 2.58, -0.25]} rotation={[2.21, 1.24, -1.36]} scale={[0.01, 0.02, 0.02]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Plane010.geometry} material={materials.Plant} position={[4.53, 2.63, -0.45]} rotation={[1.21, 1.29, -0.32]} scale={[0.01, 0.04, 0.04]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Plane011.geometry} material={materials.Plant} position={[4.83, 2.59, -0.31]} rotation={[0.33, 0.65, 0.67]} scale={[0.01, 0.02, 0.02]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.CatHouse.geometry} material={materials.CatHouse} position={[7.22, 0.77, -0.55]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.53} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube046.geometry} material={materials.CatHouse} position={[7.22, 0.37, -0.57]} scale={[0.31, 0.09, 0.38]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cylinder013.geometry} material={materials.White} position={[7.67, 0.12, -0.11]} rotation={[0, Math.PI / 2, 0]} scale={[0.06, 0.12, 0.06]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube041.geometry} material={materials.CatHouse} position={[7.23, 2.14, -0.56]} scale={[0.53, -0.03, 0.53]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cylinder014.geometry} material={materials.CatHouse} position={[6.8, 1.65, -0.12]} scale={[0.09, 0.35, 0.09]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cylinder015.geometry} material={materials.Keyboard} position={[7.65, 1.65, -0.99]} scale={[0.09, 0.35, 0.09]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cylinder016.geometry} material={materials.CatBody} position={[7.02, 2.31, -0.77]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.24, 0.26, 0.24]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Icosphere.geometry} material={materials.Cat} position={[7.43, 2.31, -1]} rotation={[0, 1.24, -0.23]} scale={0.14} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.CatHouse001.geometry} material={materials['Material.001']} position={[7.22, 0.77, -0.55]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.53} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.PC.geometry} material={materials['Material.001']} position={[1.1, 0.85, -4.18]} scale={[0.68, 0.84, 0.33]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cylinder017.geometry} material={materials.CatHouse} position={[1.79, 1.24, -4.39]} rotation={[0, 0, -Math.PI / 2]} scale={[0.06, 0.005, 0.06]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube051.geometry} material={materials.Chair} position={[3.1, 1.15, -2.24]} scale={[0.27, 0.16, 0.59]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Plane012.geometry} material={materials.Chair} position={[3.55, 2.6, -2.25]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.72} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.SeatHolder.geometry} material={materials['Material.001']} position={[2.94, 0.47, -2.24]} scale={[0.09, 0.14, 0.09]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cylinder019.geometry} material={materials['Material.001']} position={[2.59, 0.24, -1.9]} rotation={[0, 0.8, -1.38]} scale={[0.06, 0.4, 0.06]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cylinder018.geometry} material={materials['Material.001']} position={[3.56, 0.08, -1.63]} rotation={[Math.PI / 2, 0, -0.19]} scale={[0.08, 0.05, 0.08]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cone.geometry} material={materials['Material.003']} position={[0.69, 2.56, -1.66]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.01, 0.04, 0.01]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cone001.geometry} material={materials.Material} position={[0.76, 2.56, -1.71]} rotation={[-Math.PI / 2, 0, -0.1]} scale={[0.01, 0.04, 0.01]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube056.geometry} material={materials.Cat} position={[1.4, 2.09, -1.05]} rotation={[-Math.PI, 1.41, -Math.PI]} scale={[0.12, 0.01, 0.26]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube077.geometry} position={[1.4, 2.09, -1.05]} rotation={[-Math.PI, 1.41, -Math.PI]} scale={[0.12, 0.01, 0.26]} >
        <meshStandardMaterial color="white"/>
      </mesh>
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube079.geometry} material={nodes.Cube079.material} position={[0.02, 5.35, -2.54]} scale={[0.01, 0.79, 1.48]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube080.geometry} material={materials['Material.005']} position={[0.5, 1.55, -5.86]} rotation={[0, 0, -0.1]} scale={[0.4, 0.23, 0.49]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube081.geometry} material={materials['Material.005']} position={[0.55, 1.55, -7.14]} rotation={[0, -0.1, -0.1]} scale={[0.4, 0.23, 0.49]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Bed.geometry} material={materials.Desk} position={[3.25, 0.64, -6.44]} scale={[3.19, 0.46, 1.43]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube082.geometry} material={materials['Material.004']} position={[3.25, 1.18, -6.44]} scale={[3.12, -0.07, 1.67]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cylinder020.geometry} material={materials.CatBody} position={[6.3, 0.09, -5.2]} scale={0.08} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cone002.geometry} material={materials.Rubber} position={[0.76, 2.56, -1.71]} rotation={[-Math.PI / 2, 0, -0.1]} scale={[0.01, 0.04, 0.01]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cone003.geometry} material={materials.Rubber} position={[0.69, 2.56, -1.66]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.01, 0.04, 0.01]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube078.geometry} material={materials.MousePad} position={[1.47, 2.09, -3.61]} scale={[0.53, -0.01, 0.77]} />
      <mesh frustumCulled={false} receiveShadow={true} castShadow={true} geometry={nodes.Cube083.geometry} material={materials.Painting} position={[0.02, 5.35, -2.54]} scale={[0.01, 0.79, 1.48]} />
    </animated.group>
  )
}

function VideoMaterial({ url }) {
  const texture = useVideoTexture(url)
  return <meshBasicMaterial map={texture} toneMapped={false} />
}

function FallbackMaterial() {
  return <meshBasicMaterial color="black" />
}

useGLTF.preload('/roomFinalTexture.glb')
